substitutions:
  name: "your_name"
  
esphome:
  name: ${name}
  # platform: esp32
  # board: esp32-s3-devkitc-1

esp32:
  board: esp32dev
  framework:
    type: arduino
    # type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  
  ap:
    ssid: substitutions.name
    password: "12345678"

captive_portal:

logger:

ota:
  password: "585353d758e3f126d2f4982f0695d956"
  platform: esphome

web_server:
  port: 80

# api:
#   encryption:
#     key: "18T6rbg6kRjpusDhj2opiK2Rr9jksMd7ikNJ7IwsSeE="

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password

