esphome:
  name: koeck
  friendly_name: koeck

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf # Empfohlen für S3-Features, 'arduino' geht aber auch

# Aktiviert die native Web-Oberfläche direkt auf dem ESP
web_server:
  port: 80

# Ermöglicht Over-The-Air Updates
ota:
  - platform: esphome

# Die API-Anbindung für Home Assistant
api:
  # encryption:
    # key: "" # Falls du Verschlüsselung nutzt, hier den Key eintragen

# Standard-Logger (gibt Daten über USB/Seriell aus)
logger:

# WLAN-Konfiguration
wifi:
  ssid: "iot"
  password: "smarthome"
  
  # # Feste IP-Zuweisung (Optional, da du die .200 erwähnt hast)
  # manual_ip:
  #   static_ip: 192.168.2.200
  #   gateway: 192.168.2.1
  #   subnet: 255.255.255.0

# Ermöglicht die Auffindbarkeit im Netzwerk (mDNS)
mdns:
  disabled: false
